repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
    -   id: check-ast
    -   id: check-merge-conflict
    -   id: debug-statements

-   repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
    -   id: isort

-   repo: https://github.com/psf/black
    rev: 23.11.0
    hooks:
    -   id: black

-   repo: https://github.com/pycqa/flake8
    rev: 6.1.0
    hooks:
    -   id: flake8
        # Use our project's .flake8 configuration
        args: [--config=.flake8]

-   repo: local
    hooks:
    -   id: mypy
        name: mypy
        entry: python -m mypy
        language: system
        types: [python]
        exclude: ^tests/
        # Allow commit to proceed even if mypy finds errors
        verbose: true
        fail_fast: false
        pass_filenames: false
        stages: [manual]
